language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install pep8
  - pip install pep8-naming
  - pip install flake8
# command to run tests
script:
  - flake8 src
